import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [input, setInput] = useState("");
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  const ctx = api.useContext();
  const { data, isLoading: productsLoading } = api.product.getAll.useQuery();
  const { mutate, isLoading: createProductLoading } = api.product.create.useMutation({
    onSuccess: () => {
      setInput("Well done");
      void ctx.product.getAll.invalidate();
    },
  });
  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#f2f2f2] to-[#d9d9d9]">
        {isSignedIn ? <UserButton /> : <SignInButton />}
        {createProductLoading && <div>loading....</div>}
        {!createProductLoading && <input type="text" name="product-name" id="product-name" value={input} onChange={(e) => setInput(e.target.value)}/>}
        <button onClick={() => mutate({ name: input })} type="submit">Submit</button>
        <div>
          {data?.map(post => {
            return (<div>{post.name}</div>)
          })}
        </div>
      </main>
    </>
  );
}

export default Home;
